version: '2.1'

services:

### Applications Code Container #############################

  data: 
    image: tianon/true             # scratch base images are not working on AWS
    volumes:
      - ${PWD}/data:/app/data           # shared volume for data and index mapping



### Networks Setup ############################################

networks:
  backend:
    driver: "bridge"

  frontend:
    driver: "bridge"

  knowledge:
    driver: "bridge"

  proxy-network:
    external:
      name: proxy-network

### Volumes Setup #############################################

volumes:
  papernet_data:
    driver: 'local'
  mysql:
    driver: "local"
  percona:
    driver: "local"
  mssql:
    driver: "local"
  postgres:
    driver: "local"
  memcached:
    driver: "local"
  redis:
    driver: "local"
  neo4j:
    driver: "local"
  mariadb:
    driver: "local"
  mongo:
    driver: "local"
  minio:
    driver: "local"
  rethinkdb:
    driver: "local"
  phpmyadmin:
    driver: "local"
  adminer:
    driver: "local"
  aerospike:
    driver: "local"
  caddy:
    driver: "local"
  elasticsearch-data:
    driver: "local"
  elasticsearch-plugins:
    driver: "local"
