version: '2.1'

services:

### Applications Code Container #############################

  frontend: # Caddy based 
    image: papernet-front:caddy-latest
    container_name: frontend
    build: 
      context: app
      dockerfile: Dockerfile
    #extra_hosts:
    #  - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on: ["backend"]
    command: ["/usr/bin/caddy", "-conf", "/etc/Caddyfile"]
    networks:
     - default
    labels:
      - "org.label-schema.vendor=bobinette"
      - "org.label-schema.url=https://github.com/bobinette/papernet-front"
      - "org.label-schema.name=Papernet - Front-end - Dev Container"
      - "org.label-schema.description=Front-end of the papernet project."
      - "org.label-schema.version=0.9.3"
      - "org.label-schema.docker.schema-version=1.0"

  web:
    image: papernet-web:scratch-latest
    container_name: web
    ports:
      - 1705:1705
    restart: unless-stopped
    entrypoint: /app/papernet_web
    # command: ["--port", "1705"]
    networks:
      - default
    volumes:
      - ./api/data:/app/data
      - ./api/configuration/certs:/app/conf
    labels:
      - "org.label-schema.vendor=bobinette"
      - "org.label-schema.url=https://github.com/bobinette/papernet"
      - "org.label-schema.name=Papernet - Web API"
      - "org.label-schema.description=Very simple tool to keep track of the papers you read."
      - "org.label-schema.version=0.9.1"
      - "org.label-schema.docker.schema-version=1.0"

### Networks Setup ############################################

#networks:
#  frontend:
#    driver: "bridge"

#  backend:
#    driver: "bridge"

  #proxy-network:
  #  external:
  #    name: proxy-network

### Volumes Setup #############################################

volumes:
  papernet_data:
    driver: 'local'

#volumes:
  #mysql:
  #  driver: "local"
  #percona:
  #  driver: "local"
  #mssql:
  #  driver: "local"
  #postgres:
  #  driver: "local"
  #memcached:
  #  driver: "local"
  #redis:
  #  driver: "local"
  #neo4j:
  #  driver: "local"
  #mariadb:
  #  driver: "local"
  #mongo:
  #  driver: "local"
  #minio:
  #  driver: "local"
  #rethinkdb:
  #  driver: "local"
  #phpmyadmin:
  #  driver: "local"
  #adminer:
  #  driver: "local"
  #aerospike:
  #  driver: "local"
  #caddy:
  #  driver: "local"
  #elasticsearch-data:
  #  driver: "local"
  #elasticsearch-plugins:
  #  driver: "local"
